export const SEARCH_USER_PROCESSING = "SEARCH_USER_PROCESSING"
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS"
export const SEARCH_USER_FAIL = "SEARCH_USER_FAIL"

export const SINGLE_CHAT_CREATE_PROCESSING = "SINGLE_CHAT_CREATE_PROCESSING"
export const SINGLE_CHAT_CREATE_SUCCESS = "SINGLE_CHAT_CREATE_SUCCESS"
export const SINGLE_CHAT_CREATE_FAIL = "SINGLE_CHAT_CREATE_FAIL"

export const ALL_CHATS_REQUEST_PROCESSING = "ALL_CHATS_REQUEST_PROCESSING"
export const ALL_CHATS_REQUEST_SUCCESS = "ALL_CHATS_REQUEST_SUCCESS"
export const ALL_CHATS_REQUEST_FAIL = "ALL_CHATS_REQUEST_FAIL"

export const CREATE_GROUP_REQUEST_PROCESSING = "CREATE_GROUP_REQUEST_PROCESSING"
export const CREATE_GROUP_REQUEST_SUCCESS = "CREATE_GROUP_REQUEST_SUCCESS"
export const CREATE_GROUP_REQUEST_FAIL = "CREATE_GROUP_REQUEST_FAIL"

export const RENAME_GROUP_REQUEST_PROCESSING = "RENAME_GROUP_REQUEST_PROCESSING"
export const RENAME_GROUP_REQUEST_SUCCESS = "RENAME_GROUP_REQUEST_SUCCESS"
export const RENAME_GROUP_REQUEST_FAIL = "RENAME_GROUP_REQUEST_FAIL"

export const ADD_NEW_MEMBER_GROUP_REQUEST_PROCESSING = "ADD_NEW_MEMBER_GROUP_REQUEST_PROCESSING"
export const ADD_NEW_MEMBER_GROUP_REQUEST_SUCCESS = "ADD_NEW_MEMBER_GROUP_REQUEST_SUCCESS"
export const ADD_NEW_MEMBER_GROUP_REQUEST_FAIL = "ADD_NEW_MEMBER_GROUP_REQUEST_FAIL"

export const REMOVE_MEMBER_FROM_GROUP_REQUEST_PROCESSING = "REMOVE_MEMBER_FROM_GROUP_REQUEST_PROCESSING"
export const REMOVE_MEMBER_FROM_GROUPP_REQUEST_SUCCESS = "REMOVE_MEMBER_FROM_GROUP_REQUEST_SUCCESS"
export const REMOVE_MEMBER_FROM_GROUP_REQUEST_FAIL = "REMOVE_MEMBER_FROM_GROUP_REQUEST_FAIL"

export const SELECT_USER_FOR_CHAT = "SELECT_USER_FOR_CHAT"

export const SEND_MESSAGE_REQUEST_PROCESSING = "SEND_MESSAGE_REQUEST_PROCESSING"
export const SEND_MESSAGE_REQUEST_SUCCESS = "SEND_MESSAGE_REQUEST_SUCCESS"
export const SEND_MESSAGE_REQUEST_FAIL = "SEND_MESSAGE_REQUEST_FAIL"

export const GET_MESSAGE_REQUEST_PROCESSING = "GET_MESSAGE_REQUEST_PROCESSING"
export const GET_MESSAGE_REQUEST_SUCCESS = "GET_MESSAGE_REQUEST_SUCCESS"
export const GET_MESSAGE_REQUEST_FAIL = "GET_MESSAGE_REQUEST_FAIL"

export const AI_REQUEST_PROCESSING = "AI_REQUEST_PROCESSING";
export const AI_REQUEST_SUCCESS = "AI_REQUEST_SUCCESS";
export const AI_REQUEST_FAIL = "AI_REQUEST_FAIL";
export const ADD_AI_MESSAGE = "ADD_AI_MESSAGE";

export const JOIN_GROUP_REQUEST = "JOIN_GROUP_REQUEST";
export const JOIN_GROUP_SUCCESS = "JOIN_GROUP_SUCCESS";
export const JOIN_GROUP_FAIL = "JOIN_GROUP_FAIL";

export const EXIT_GROUP_REQUEST = "EXIT_GROUP_REQUEST";
export const EXIT_GROUP_SUCCESS = "EXIT_GROUP_SUCCESS";
export const EXIT_GROUP_FAIL = "EXIT_GROUP_FAIL";

export const DELETE_GROUP_REQUEST = "DELETE_GROUP_REQUEST";
export const DELETE_GROUP_SUCCESS = "DELETE_GROUP_SUCCESS";
export const DELETE_GROUP_FAIL = "DELETE_GROUP_FAIL";

export const JOIN_GROUP_ANONYMOUS_REQUEST = "JOIN_GROUP_ANONYMOUS_REQUEST";
export const JOIN_GROUP_ANONYMOUS_SUCCESS = "JOIN_GROUP_ANONYMOUS_SUCCESS";
export const JOIN_GROUP_ANONYMOUS_FAIL = "JOIN_GROUP_ANONYMOUS_FAIL";


export const WEB_SOCKET_RECEIVED_MESSAGE = "WEB_SOCKET_RECEIVED_MESSAGE"

export const WEB_SOCKET_NOTIFICATION_RECEIVED = "WEB_SOCKET_NOTIFICATION_RECEIVED"

export const WEB_SOCKET_CONNECTED = "WEB_SOCKET_CONNECTED"

